Repository ismet55555/yojenkins, pull requests merged in 2022-12, with the labels that each got.

#173 build rebuild now parses the job number from the URL
  yojenkins/cli/cli_build.py
Labels: enhancement

#174 feat: Pass Any URL That Includes the Build URL via `--url` Option
  .bumpversion.cfg
  VERSION
  docs/source/cli_outline.md
  docs/source/usage.md
  setup.py
  yojenkins/__init__.py
  yojenkins/__main__.py
  yojenkins/cli/cli_build.py
  yojenkins/cli_sub_commands/build.py
  yojenkins/utility/utility.py
  yojenkins/yo_jenkins/build.py
  yojenkins/yo_jenkins/stage.py
Labels: enhancement

#176 fix: yojenkins build parameters --url <URL>
  yojenkins/yo_jenkins/build.py
Labels: bug

#177 feat: `yojenkins build --url <BUILD URL>` can be implied by just `yojenkins build <BUILD URL>`
  yojenkins/cli/cli_build.py
Labels: enhancement

#178 Bump version: 0.0.78 → 0.0.79
  .bumpversion.cfg
  VERSION
  docs/source/cli_outline.md
  setup.py
  yojenkins/__init__.py
Labels: Version Bump

#179 feat: `diff` info and logs for jobs and builds
  .bumpversion.cfg
  .gitignore
  VERSION
  docs/source/cli_outline.md
  setup.py
  yojenkins/__init__.py
  yojenkins/cli/cli_build.py
  yojenkins/cli/cli_job.py
  yojenkins/cli/cli_utility.py
  yojenkins/cli_sub_commands/build.py
  yojenkins/cli_sub_commands/job.py
  yojenkins/utility/utility.py
  yojenkins/yo_jenkins/build.py
  yojenkins/yo_jenkins/job.py
Labels: enhancement

#180 feat: Build diff line-pattern REGEX, provide your own API token for profile
  .bumpversion.cfg
  VERSION
  docs/source/cli_outline.md
  setup.py
  yojenkins/__init__.py
  yojenkins/cli/cli_auth.py
  yojenkins/cli/cli_build.py
  yojenkins/cli/cli_decorators.py
  yojenkins/cli_sub_commands/auth.py
  yojenkins/cli_sub_commands/build.py
  yojenkins/monitor/build_monitor.py
  yojenkins/monitor/job_monitor.py
  yojenkins/utility/utility.py
  yojenkins/yo_jenkins/auth.py
  yojenkins/yo_jenkins/build.py
  yojenkins/yo_jenkins/job.py
Labels: bug, enhancement
