Repository ismet55555/yojenkins, pull requests merged in 2022-11, with the labels that each got.

#164 fix yoenkins build logs with --follow
  yojenkins/yo_jenkins/build.py
Labels: bug

#169 fix: Stream build logs using `progressiveText` endpoint, fall-back on legacy method
  yojenkins/cli_sub_commands/build.py
  yojenkins/yo_jenkins/build.py
  yojenkins/yo_jenkins/rest.py
Labels: bug, enhancement

#165 feat: Add show result console logs to build rebuild
  yojenkins/cli/cli_build.py
  yojenkins/cli_sub_commands/build.py
Labels: enhancement

#170 feat: Follow/Stream Logs to Console after Job Build and Rebuild
  .bumpversion.cfg
  Pipfile
  Pipfile.lock
  VERSION
  docs/source/cli_outline.md
  setup.py
  yojenkins/__init__.py
  yojenkins/cli/cli_build.py
  yojenkins/cli/cli_job.py
  yojenkins/cli/cli_server.py
  yojenkins/cli_sub_commands/build.py
  yojenkins/cli_sub_commands/job.py
  yojenkins/utility/utility.py
Labels: enhancement

#172 hot fix: Added yaspin to requirements.txt
  .bumpversion.cfg
  Pipfile.lock
  VERSION
  docs/source/cli_outline.md
  requirements.txt
  setup.py
  yojenkins/__init__.py
Labels: bug
